name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2
        name: Customize Docker driver
        with:
          driver-opts: image=moby/buildkit:v0.11.0

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: soulteary/gvm-easy-installer
          tags: 1.0.24, latest
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: soulteary/gvm-easy-installer
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          username: soulteary
          password: ${{ secrets.GITHUB_TOKEN }}
